### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by alibbz1** [Leiren/Npanel#1]
hi bro this not work 

![Screenshot_2023-02-13-12-52-40-632_com sonelli juicessh](https://user-images.githubusercontent.com/32574960/218419525-867cf382-e128-4aeb-b332-c850abf4a9a2.jpg)

**Comment by Leiren** [comment]
Hi, 
Thanks for reporting it. 
looks like the final executable was missing when i created the zip file, strange to me.

fixed, you can run install script again.

**Comment by alibbz1** [comment]
tanx bro it's ok
