### ISSUE TITLE
user traffic (10768MB , 10.51GB)

### ISSUE THREAD

**Issue by heydariomid4** [Leiren/Npanel#10]
Show the amount of user traffic consumption up to 1 gig in megabytes, then 1024 megabytes in gigabytes.
![image](https://user-images.githubusercontent.com/44144753/219758977-022f8429-53b4-47fd-8ec9-712d26f59344.png)

**Comment by Leiren** [comment]
Thanks for reproting it, will be fixed in next version

**Comment by Leiren** [comment]
closing this as fixed (0.1.7 Alpha release)
