### ISSUE TITLE
ip limit issue

### ISSUE THREAD

**Issue by ada-mr0r** [Leiren/Npanel#11]
@Leiren tnx for this fantastic product.
it seems the IP limit is not working as expected.
I set it to 1 but I can connect using two different devices which connect using different networks

**Comment by Leiren** [comment]
I have checked it before. it was working as expected. 
>This is a ip limit not a device limit, it allows the second device to transfer data the moment first device stops sending packets + a timeout.
you should download a file or watch a stream/youtube or someting with first device then try to connect with second device.

anyways ill check it again before releasing next version.

**Comment by ada-mr0r** [comment]
@Leiren great! tnx
