### ISSUE TITLE
bbr

### ISSUE THREAD

**Issue by alibbz1** [Leiren/Npanel#13]
Hello my friend, can you add a part to the script to install different versions of BBR?

**Comment by Leiren** [comment]
I will add an option to disable the auto-execution of bbr script so you will be able to install it using your own scripts.

But, the current bbr script also works fine and stable as far as i know.

**Comment by alibbz1** [comment]
Thank you for your friend, yes, but if you can put a variety of BBR scripts and also LotServer, the user will be able to choose one of the options that works better according to their needs

**Comment by alibbz1** [comment]
Thank you for your friend, yes, but if you can put a variety of BBR scripts and also LotServer, the user will be able to choose one of the options that works better according to their needs

**Comment by Leiren** [comment]
well thats a other topic and not related to npanel,  users maychoose the script that they like because

there are many implementations of bbr and i don't have enough knowledge to test or confir all of them and the current bbr is generally fine.
