### ISSUE TITLE
Panel is not loaded after changing port

### ISSUE THREAD

**Issue by davoodice** [Leiren/Npanel#15]
I give permission in Windows firewall to specific port. But panel can not be loaded.
This is console messages after changing port:

network checks...
windows kill port:80 not implemented yet. we assume this port is free.
windows kill port:443 not implemented yet. we assume this port is free.
windows kill port:2060 not implemented yet. we assume this port is free.
windows kill port:2061 not implemented yet. we assume this port is free.
[INFO]  2023/02/24 00:06:29 trojan-go v1.0.5 initializing
[WARN]  2023/02/24 00:06:29 empty tls fallback port
[WARN]  2023/02/24 00:06:29 empty tls http response
begin apply

**Comment by Leiren** [comment]
I will check it

**Comment by Leiren** [comment]
some questions:
1- are you on windows server or home windows computer?
2- are you visiting the panel this way or not ? https://sub.domain.com:newport/username/ 
last slash in url is important

**Comment by Leiren** [comment]
when i check on my windows it works fine but i should check on a real windows server which i don't have access to it yet. but ofcourse ill check it on real windows server today

**Comment by davoodice** [comment]
Thank you. Yes, I did every thing correctly.
I found port 2087 works, but I need other port like 889. And it does not work.

**Comment by davoodice** [comment]
i use windows server (real server)

**Comment by Leiren** [comment]
are you behind a cdn ? cloudflare ?

**Comment by davoodice** [comment]
No. I don't use CDN.

**Comment by Leiren** [comment]
have you checked the firewall settings of your server provider , not windows it self?

**Comment by Leiren** [comment]
and also , please turn windows firewall off entirely and check if that changes something or not.

**Comment by davoodice** [comment]
I didn't buy any firewall. I am sure ports are open (tested in linux). I allow all ports in windows firewall. but I will turn it off and get back to you.

**Comment by davoodice** [comment]
Okay. I turn it off.
Nothing changed.
A New problem appeared. 
when I enter my user address, it redirects me to the main domain address.
this is my settings:

{"admin_username":"davood","admin_password":"3858182","domain":"try.blablabla002.tk","mainport":443,"websocket_path":"/users","fakewebsite_template":1,"cert_path":"c:\\certbot\\fullchain1.pem","private_key_path":"c:\\certbot\\privkey1.pem","mux":true,"bbr_on_start":true,"telegram_bot_admin_key":""}

and this is console message:

[WARN]  2023/02/24 02:22:40 redirecting connection from  46.***.***.24:33294 to 127.0.0.1:2060
[ERROR] 2023/02/24 02:22:40 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:142 trojan failed to accept conn | not a valid websocket handshake request: 46.***.***.24:33296
[WARN]  2023/02/24 02:22:40 redirecting connection from 46.***.***.24:33296 to 127.0.0.1:2060
template/creative-studio/

**Comment by davoodice** [comment]
I got this now in console
[ERROR] 2023/02/24 02:35:47 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:124 failed to perform tls handshake with 118.81.226.162:59086, redirecting | tls: first record does not look like a TLS handshake

**Comment by Leiren** [comment]
when you visit your website regularly , you see this error , and it says that the visitor is not a vaild vpn client, it is a browser visitor and so we forward it to reverse proxy

**Comment by davoodice** [comment]
got it. thanks
