### ISSUE TITLE
panel is not load

### ISSUE THREAD

**Issue by mohammadsh1237** [Leiren/Npanel#17]
I install panel after 1 day panel is not load
restart, reinstall, update, reboot server doesn't work

**Comment by Leiren** [comment]
please dm [t.me/tired_mans](me) on telegram so that i can check your server logs

**Comment by Leiren** [comment]
a change in websocket for web-ui is coming to fix this problem, soon.

**Comment by Leiren** [comment]
fixed in 0.2.3
