### ISSUE TITLE
some errors in status

### ISSUE THREAD

**Issue by ScriptWhale** [Leiren/Npanel#18]
hi there i have some problems, here is the errors in npanel status : 
Mar 02 17:54:47 vm82077 Npanel[22596]: template/direct-tv/
Mar 02 17:54:47 vm82077 Npanel[22596]: [ERROR] 2023/03/02 17:54:47 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:142 trojan failed to ac>Mar 02 17:54:47 vm82077 Npanel[22596]: [WARN]  2023/03/02 17:54:47 redirecting connection from 172.70.250.130:64118 to 127.0.0.1:2060
Mar 02 17:54:47 vm82077 Npanel[22596]: template/direct-tv/
Mar 02 17:54:47 vm82077 Npanel[22596]: [ERROR] 2023/03/02 17:54:47 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:142 trojan failed to ac>Mar 02 17:54:47 vm82077 Npanel[22596]: [WARN]  2023/03/02 17:54:47 redirecting connection from 162.158.86.176:56558 to 127.0.0.1:2060
Mar 02 17:54:47 vm82077 Npanel[22596]: template/direct-tv/
Mar 02 17:54:47 vm82077 Npanel[22596]: [ERROR] 2023/03/02 17:54:47 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:142 trojan failed to ac>Mar 02 17:54:47 vm82077 Npanel[22596]: [WARN]  2023/03/02 17:54:47 redirecting connection from 172.71.246.126:31858 to 127.0.0.1:2060
Mar 02 17:54:47 vm82077 Npanel[22596]: template/direct-tv/

can you help me by these ?

**Comment by Leiren** [comment]
Hi, 
these errors are comfing from the trojan-go and the term "Error" is not a well chosen name for them
those are like "warnings" 
when trojan-go detects a regular website visitor rather than a vpn client, it prints out "Error".
you should safely ignore them.

when you see a log with a tag like "[Fatal]" that is actual error and will stop the core.

**Comment by ScriptWhale** [comment]
thanks for the replay , is there anyway to to solve those failings? and is there anyway to increase the connection speed? cause i think it has lower speed than ws of xui or somthing like that. thanks <3

**Comment by Leiren** [comment]
i think the opposite way, the speed is depended on many more foctorts,
and according to test results that i have done from many locations and many destination server, 
the speed,ping and jitter are absolutely fine
