### ISSUE TITLE
system don't work after change port

### ISSUE THREAD

**Issue by roozbehsat** [Leiren/Npanel#23]
Hi guys
my panel stop working after change the port in linux server.
I change it to 8080 then it's stop working.

**Comment by Leiren** [comment]
are you usuing a cdn ? 8080 is not a https port

you can change the port and all settings manually in /opt/Npanel/panel.json

**Comment by roozbehsat** [comment]
yes I am using cdn

**Comment by roozbehsat** [comment]
> /opt/Npanel/panel.json

may I ask u to explain more?

**Comment by roozbehsat** [comment]
I change the port to 80 once then to 2087 an restart the service but none of them not working. in my country some provider having noise on some port like 443, please help me.

**Comment by Leiren** [comment]
As far as i know, you should always work on port 443, if you are not getting a good connection on that port, that means the firewall (gfw) is blocking it for many possible reasons,  including domain, cloudflare domain or ip, etc...

**Comment by roozbehsat** [comment]
One more question: 
If we can't change the port why it include the panel?

**Comment by Leiren** [comment]
You can change the port, but it is not suggested,
 I will debug this before releasing the new update

**Comment by roozbehsat** [comment]
What changes in the new version?

**Comment by Leiren** [comment]
It's hard to describe, it has node and router management that enables customizing trojan protocol
that allows advanced users to enable double encryption plugin, change tls strategy, share 1 database to all servers they have, use ip limit on tunnel server (if they have), etc..

**Comment by roozbehsat** [comment]
When u release new version?

**Comment by Leiren** [comment]
around 2 days or even less
