### ISSUE TITLE
Speed Limits not working

### ISSUE THREAD

**Issue by roozbehsat** [Leiren/Npanel#25]
Hi and thank for your nice panel,
I set the limit for ussers (1mb/s) for download, but when I check usser on speedtest I see that is not work on that speed. May I ask u to check it?

**Comment by Leiren** [comment]
alright sure

**Comment by Leiren** [comment]
i checked it, when i set the limit to 1024 which means 1 megabyte per sec

the speed thest download speed will not be higher that 1megabyte/sec or 8 megabit/sec which is the same

**Comment by roozbehsat** [comment]
Thanks a lot, it's working great, my fault is in calculation on megabit and megabytes. Thanks a lot for your support. 🙏🙏🙏
