### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by sasaney** [Leiren/Npanel#29]
hii 

hope  you finding well 

when we try to log in to admin page its only show me a black page with no filed to enter password to entry . i reinstall panel also but its not solved . and only show a black blank page . 
how we can fix it ?

**Comment by sasaney** [comment]
![Capture](https://user-images.githubusercontent.com/130912277/235303573-c33242b4-ba3c-495f-9f95-3c279d262bfc.JPG)

**Comment by Leiren** [comment]
dm me [here](https://telegram.me/tired_mans) so to check

**Comment by Leiren** [comment]
fixed, the cause was cloudflare wrong settings(applications)
