### ISSUE TITLE
side application error

### ISSUE THREAD

**Issue by alibbz1** [Leiren/Npanel#5]
hi my friend i have this error

![Screenshot_2023-02-15-10-54-18-766_com sonelli juicessh](https://user-images.githubusercontent.com/32574960/218981958-27f1b7df-ee63-49dc-8aac-2f4badec385e.jpg)

**Comment by Leiren** [comment]
run update script and then
>service npanel start

**Comment by Leiren** [comment]
it should fix most problems causing server not being able to start

**Comment by alibbz1** [comment]
i try update and start again have this problem

**Comment by Leiren** [comment]
run these commands and show me the output
>service npanel stop
cd /opt/Npanel/
./Npanel

**Comment by alibbz1** [comment]
root@V2rayserver:~# service npanel stop
root@V2rayserver:~# cd /opt/Npanel/
root@V2rayserver:/opt/Npanel# ./Npanel
network checks...
free port: 80
free port: 443
free port: 2060
free port: 2061
BBR ...
(output: "", exitCode: 0)
(output: "\e[H\e[J\e[3J---------- System Information ----------\n OS      : Ubuntu 20.04.5 LTS\n Arch    : x86_64 (64 Bit)\n Kernel  : 5.4.0-139-generic\n----------------------------------------\n Automatically enable TCP BBR script\n\n URL: https://teddysun.com/489.html\n----------------------------------------\n\nPress any key to start...or Press Ctrl+C to cancel\n\n\e[1;31;32m[Info] \e[0mTCP BBR has already been enabled. nothing to do...\n", exitCode: 0)
disabling ipv6 ...
net.ipv6.conf.all.disable_ipv6 = 1

net.ipv6.conf.default.disable_ipv6 = 1

net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

Firewall stopped and disabled on system startup

could not parse users.db; did you corrupt it? , loaded no users.
input(1, 0) Error: { expected

**Comment by Leiren** [comment]
so the users.db file is somehow corrupt. if you dont mind the users you have created , you sohuld delet users.db (in /opt/Npanel/)

otherwise you should resotre your backup , i already told in backup section that users.db and panel.json are the 2 files that you should backup before you update.

since i tested my own vps with update script, it is not a corruption made by the update script, it may be you that edited the file or other reasons.

**Comment by alibbz1** [comment]
Why did this problem occur?

**Comment by Leiren** [comment]
can you tell me how to reproduce this problem? , what exactly did you do before this happens?

**Comment by Leiren** [comment]
this error happens because the file holding your users data and settings has invalid data.

**Comment by alibbz1** [comment]
I didn't do anything on the server, one of the users called me and said that he couldn't connect, and I checked the server and found this error.

**Comment by alibbz1** [comment]
Yes, I have a backup copy, but unfortunately it is not available to me now

**Comment by Leiren** [comment]
the first thing you have to do in this case is to restore your backup of users.db.
if you dont have a backup. then delete users.db file and start npanel . then re-create the users you had before.
>service npanel stop
cd /opt/Npanel/
rm users.db
service npnael start

**Comment by Leiren** [comment]
please try to take a backup of users.db every day untill i address this problem and fix it .

**Comment by alibbz1** [comment]
Thank you my friend for your attention, I hope this problem will be solved soon

**Comment by Leiren** [comment]
if you haven't already deleted users.db 
please send it to me here so i can investigate

**Comment by alibbz1** [comment]
Unfortunately, I deleted it a few moments ago and now I am creating new users.  But I have the backup copy and I can send it to you in the next few hours

**Comment by Leiren** [comment]
ok that would be fine, Thanks

**Comment by Leiren** [comment]
Update to 0.1.5 since this version is more stable.

**Comment by alibbz1** [comment]
Hello, my friend, I just got access to the system. This user file was corrupted
[users.txt](https://github.com/Leiren/Npanel/files/10757024/users.txt)

**Comment by Leiren** [comment]
Thank you, i investigate and will release new version when i feagure out the reason behind it.

**Comment by alibbz1** [comment]
Thank you very much, my friend, I hope you can successfully complete this project

**Comment by Leiren** [comment]
This problem is fixed after the auto-backup and restore implementation (v 02.2) , the cause of it was restarting the system when the users.db file was being overwritten.
